baseURL: 'http://0xarthur.xyz/'
languageCode: en-us
title: Home
paginate: 10
theme: PaperMod

ignoreErrors: ["error-remote-getjson"]

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-152084126-5

menu:
    main:
        - identifier: categories
          name: Archive
          url: archives
          weight: 1
        # - identifier: Tags
        #   name: Tags
        #   url: /tags
        #   weight: 20
        # - name: Search
        #   url: search/
        #   weight: 2
        - name: Who Dis?
          url: about
          weight: 3


taxonomies:
    category: categories
    tag: tags
    series: series

params:
    env: production
    title: 0xArthur.xyz
    author: Me
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light

    ShowReadingTime: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableScrollToTop: true
    hideSummary: true
    showtoc: false
    tocopen: false

    # Maths typesetting
    math: true

    # Profile Mode
    profileMode:
        enabled: true
        title: "Arthur Gousset" # optional default will be site title
        subtitle: "Crypto PM working on [identity](https://docs.celo.org/celo-codebase/protocol/identity) for [Celo](https://celo.org/) 🧑‍🚀"
        imageUrl: "https://pbs.twimg.com/profile_images/1433747018468450305/EvOLBFZE_400x400.jpg" # optional
        imageTitle: # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Blog
              url: posts/

    # Uncomment if you want posts on the homepage instead of profileMode
    # homeInfoParams:
    #     Title: "0xArthur.xyz"
    #     Content: >
    #         Welcome to demo of hugo's theme PaperMod.

    #         - **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.
           
    #         - Do give a 🌟 on Github !

    #         - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "https://pbs.twimg.com/profile_images/1433747018468450305/EvOLBFZE_400x400.jpg"


    socialIcons: # optional
        - name: twitter
          url: "https://twitter.com/Arthur__Gousset"
        - name: github
          url: "https://github.com/arthurgousset"
        - name: linkedin
          url: "https://www.linkedin.com/in/arthur-gousset/"

    editPost:
        URL: "https://github.com/0xarthurxyz/0xArthurxyz.github.io/blob/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary