baseURL: 'http://0xarthur.xyz/'
languageCode: en-us
title: Home
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-152084126-5

params:params:
    env: production
    title: 0xArthur.xyz
    author: Me
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light

    ShowReadingTime: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableScrollToTop: true
    hideSummary: false
    showtoc: true
    tocopen: false

    # Proile Mode
    profileMode:
        enabled: true
        title: "Arthur Gousset" # optional default will be site title
        subtitle: "Working on identity for Celo 🧑‍🚀"
        imageUrl: "https://pbs.twimg.com/profile_images/1433747018468450305/EvOLBFZE_400x400.jpg" # optional
        imageTitle: # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:



    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "https://pbs.twimg.com/profile_images/1433747018468450305/EvOLBFZE_400x400.jpg"


    socialIcons: # optional
        - name: twitter
          url: "https://twitter.com/Arthur__Gousset"
        - name: github
          url: "https://github.com/arthurgousset"
        - name: linkedin
          url: "https://www.linkedin.com/in/arthur-gousset/"

    editPost:
        URL: "https://github.com/0xarthurxyz/0xArthurxyz.github.io/blob/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link
    
menu:
    main:
        - identifier: categories
          name: Archive
          url: /posts
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20