baseURL: 'http://example.org/'
languageCode: en-us
title: Arthur Gousset
theme: PaperMod

params:
    homeInfoParams:
        Title: 0xArthur
        Content: My name is Arthur Gousset, 

    socialIcons: # optional
        - name: linkedin
          url: "https://www.linkedin.com/in/arthur-gousset/"
        - name: twitter
          url: "https://twitter.com/Arthur__Gousset"
        - name: github
          url: "https://github.com/arthurgousset"