baseURL: 'http://arthurgousset.com/'
languageCode: en-us
title: Home
paginate: 10
theme: PaperMod

ignoreErrors: ["error-remote-getjson"]

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-152084126-5

menu:
    main:
        - identifier: categories
          name: Content
          url: content
          weight: 1
        - name: Standing invitation 👋
          url: invitation
          weight: 2

taxonomies:
    category: categories
    tag: tags
    series: series

# Documentation for params: https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-variables/
params:
    env: production
    title: arthurgousset
    author: Me
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light

    ShowReadingTime: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    disableScrollToTop: true
    hideSummary: true
    hideMeta: true # To Hide meta elements : date, read-time, author and available-translations for page
    showtoc: false
    tocopen: false

    # RSS setting
    ShowFullTextinRSS: true

    # Maths typesetting
    math: true

    # Comment settings
    comments: true
    giscus:
      repo: arthurgousset/website
      repoID: MDEwOlJlcG9zaXRvcnk0MDM2MzcwMzE=
      category: Comments
      categoryID: DIC_kwDOGA8DJ84CdHsV
      mapping: pathname
      inputPosition: top
      theme: preferred_color_scheme
      lang: en

    # Profile Mode
    profileMode:
        enabled: true
        title: "Arthur Gousset" # optional default will be site title
        subtitle: "Engineering @ cLabs 🚢"
        imageUrl: "https://github.com/arthurgousset.png" # optional
        imageTitle: # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size

    assets:
        disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "https://github.com/arthurgousset.png"


    socialIcons: # optional
        - name: "github"
          url: "https://github.com/arthurgousset"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/arthurgousset/"
        - name: "twitter"
          url: "https://twitter.com/arthurgoussetx"

    editPost:
        URL: "https://github.com/arthurgousset/website/tree/main/content"
        Text: "Edit on GitHub" # edit text
        appendFilePath: true # to append file path to Edit link

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

# markup:
#   highlight:
#     anchorLineNos: false
#     codeFences: true
#     guessSyntax: false
#     hl_Lines: ""
#     lineAnchors: ""
#     lineNoStart: 1
#     lineNos: false
#     lineNumbersInTable: true
#     noClasses: true
#     noHl: false
#     style: vs
#     tabWidth: 4

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    style: github-dark
